pipline:
  build:
    image: index.qiniu.com/kci/golang-bash:1.6
    commands:
      - make
  index.qiniu.com/kci/plugin_docker:
     repo: nowenl/helloworld
     kirk_autoupdate: nowen.myapp/default/helloworld
  index.qiniu.com/kci/plugin_email:
    recipients:
      - lulongwen@qiniu.com
